---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by torvald.
--- DateTime: 2019-11-03 02:04
---
if not _G.motd then _G.motd = {} end

motd = {LIX_LOGO .. "Welcome to Lix " .. LIX_VERSION .. " (" .. _VERSION .. ")"}