---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by torvald.
--- DateTime: 2020-03-10 22:46
---

local term = require("term")

if not _G.tty then -- choosing 'tty' global namespace to avoid clash with OpenComputers

dofile("etc/plterm.lua")

tty.clear = function()
    local oldx, oldy = term.getCursor()
    term.clear()
    term.setCursor(oldx, oldy)
end

tty.cleareol = term.clearLine

tty.golc = function(l, c)
    term.setCursor(c, l)
end

tty.up = function(n)
    local x, oldy = term.getCursor()
    term.setCursor(x, oldy - 1)
end

tty.down = function(n)
    local x, oldy = term.getCursor()
    term.setCursor(x, oldy + 1)
end

tty.right = function(n)
    local oldx, y = term.getCursor()
    term.setCursor(oldx + 1, y)
end

tty.left = function(n)
    local oldx, y = term.getCursor()
    term.setCursor(oldx - 1, y)
end

tty.hide = function()
    term.setCursorBlink(false)
end

tty.show = function()
    term.setCursorBlink(true)
end

tty.getcurpos = function()
    local x, y = term.getCursor()
    return y, x
end

tty.getscrlc = function()
    local w, h = term.getViewport()
    return h, w
end

-- do-nothing functions
tty.setrawmode = function() end
tty.setsanemode = function() end
tty.savemode = function() end
tty.restoremode = function() end


end