---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Torvald.
--- DateTime: 2019-11-04 12:33
---

if not _G.shell then _G.shell = {} end

shell.trim_spaces = function(s)
    -- trim indents
    if s:byte() == 32 then
        k = 2 while s:byte(k) == 32 do k = k + 1 end
        s = s:sub(k)
    end
    -- trim extra spaces
    if s:byte(s:len()) == 32 then
        k = s:len() - 1 while s:byte(k) == 32 do k = k - 1 end
        s = s:sub(1, k)
    end

    return s
end

--- parse input into args[], where:
--- input: tar -xvf out "file1 file2" file3
--- t[1] = tar'
--- t[2] = -xvf'
--- t[3] = out'
--- t[4] = file1 file2'
--- t[5] = file3'     (' indicates string end)
shell.parse = function(s)
    local t = {}
    local sb = "" -- string buffer

    local function dispatch_sb()
        if sb:len() > 0 then
            table.insert(t, sb)
            sb = ""
        end
    end

    -- null string
    if s:len() == 0 then return nil end

    s = shell.trim_spaces(s)

    -- states
    local quotation_mode -- nil, '(0x22), "(0x27)
    local escape_mode = false
    for i = 1, s:len() do
        local v = s:byte(i)

        if i == s:len() then
            if v ~= quotation_mode then
                sb = sb .. string.char(v)
            end
            dispatch_sb()
        elseif quotation_mode then
            if v == quotation_mode then
                quotation_mode = nil
                dispatch_sb()
            else
                sb = sb .. string.char(v)
            end
        elseif not quotation_mode and (v == 0x22 or v == 0x27) then
            quotation_mode = v
        elseif not quotation_mode and v == 0x20 then
            dispatch_sb()
        else
            sb = sb .. string.char(v)
        end
    end

    return t
end